export type ThemeTypes = {
    name: string;
    dark: boolean;
    variables?: object;
    colors: {
        primary?: string;
        secondary?: string;
        info?: string;
        dashboardcolorRed?: string;
        dashboardcolorYellow?: string;
        dashboardcolorDarkGreen?: string;
        dashboardcolorBlue?: string;
        success?: string;
        accent?: string;
        warning?: string;
        warning100?: string;
        error?: string;
        cinza500?: string;
        lightprimary?: string;
        lightsecondary?: string;
        lightsuccess?: string;
        lighterror?: string;
        lightinfo?: string;
        lightwarning?: string;
        textPrimary?: string;
        textSecondary?: string;
        borderColor?: string;
        hoverColor?: string;
        inputBorder?: string;
        containerBg?: string;
        background?: string;
        surface?: string;
        'on-surface-variant'?: string;
        grey100?: string;
        grey200?: string;
    };
};